# Generated by Django 5.0.6 on 2024-06-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Task Description')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deadline', models.DateTimeField(blank=True, help_text='Optional deadline for the task', null=True)),
                ('is_done', models.BooleanField(default=False, verbose_name='Completed')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.tag')),
            ],
            options={
                'ordering': ['is_done', '-datetime'],
            },
        ),
    ]
